name: Release | Core

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@4a02cbd99769e46198135c31d5097c94618ba3f5 # v1.21.0

      - name: Set up JDK
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven

      - name: Run release:prepare
        run: |
          mvn -B release:prepare \
            -Dmaven.test.skip=true \
            -Dcheckstyle.skip=true \
            -Dfmt.skip=true

      - name: Push release commits and tags
        run: |
          git push origin HEAD
          git push origin --tags
